"""Generate corpora and Java-jx1 ZX1 streams for the ST1 test harness."""
import subprocess, sys, tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
CP = str(HERE.parent.parent / 'target' / 'classes')      # mvn compile first

RING_SMALL = 256    # correctness and the N=256 timing profile
RING_FAIR = 1024    # shared N=1024 timing profile

def compress(data, m=None):
    with tempfile.TemporaryDirectory() as d:
        src, dst = Path(d, 'in'), Path(d, 'out')
        src.write_bytes(data)
        args = ['java', '-ea', '-cp', CP, 'org.jx1.Jx1', '-f']
        if m:
            args.append(f'-m{m}')
        subprocess.run(args + [str(src), str(dst)], check=True, capture_output=True)
        return dst.read_bytes()

import random
r = random.Random(42)
words = [bytes(r.randrange(256) for _ in range(r.randrange(3, 10))) for _ in range(20)]
soup = b''.join(words[r.randrange(20)] + b' ' for _ in range(400))
block = bytes(r.randrange(256) for _ in range(200))
period128 = (bytes(r.randrange(256) for _ in range(128))) * 8   # drawn (unused here) to
period129 = (bytes(r.randrange(256) for _ in range(129))) * 8   # keep the RNG stream
maxoff = bytes(r.randrange(256) for _ in range(32512))          # identical to test68k.py

# (name, data, timing iterations)  - iterations chosen for ~5M cycles per run
CASES = [
    ('text',      b'abracadabra hocus pocus abracadabra ' * 10, 400),
    ('wordsoup',  soup,                                          30),
    ('farmatch',  block + b'x' * 2500 + block,                   60),
    ('period129', period129,                                    200),
    ('allsame',   b'A' * 1000,                                  200),
    ('rle32k',    b'A' * 32000,                                    6),
    ('maxoffset', maxoff + maxoff[:500],                           6),
]

def main():
    lines = ['; Generated by gendata.py - corpora and Java-jx1 ZX1 streams.', '']
    table = ['cases:']
    rtable = ['ring_cases:']
    ftable = ['fair_cases:']
    for name, data, iters in CASES:
        comp = compress(data)
        ring = compress(data, RING_SMALL)
        fair = compress(data, RING_FAIR)
        (HERE / f'{name}.z').write_bytes(comp)
        (HERE / f'{name}.r').write_bytes(ring)
        (HERE / f'{name}.r1024').write_bytes(fair)
        (HERE / f'{name}.e').write_bytes(data)
        table.append(f'\tdc.l\tn_{name},c_{name},{len(comp)},e_{name},{len(data)},{iters}')
        rtable.append(f'\tdc.l\tn_{name},r_{name},{len(ring)},e_{name},{len(data)},{iters}')
        ftable.append(f'\tdc.l\tn_{name},f_{name},{len(fair)},e_{name},{len(data)},{iters}')
        lines.append(f'n_{name}:\tdc.b\t"{name}",0')
        lines.append('\teven')
    table.append('\tdc.l\t0')
    rtable.append('\tdc.l\t0')
    ftable.append('\tdc.l\t0')
    table += [''] + rtable + [''] + ftable
    lines.append('')
    lines += table
    lines.append('')
    for name, data, _ in CASES:
        lines.append('\teven')
        lines.append(f'c_{name}:\tincbin\t"{name}.z"')
        lines.append('\teven')
        lines.append(f'r_{name}:\tincbin\t"{name}.r"')
        lines.append('\teven')
        lines.append(f'f_{name}:\tincbin\t"{name}.r1024"')
        lines.append('\teven')
        lines.append(f'e_{name}:\tincbin\t"{name}.e"')
    lines.append('')
    (HERE / 'data.inc').write_text('\n'.join(lines))
    biggest = max(len(data) for _, data, _ in CASES)
    print(f'{len(CASES)} cases, largest expected output {biggest} bytes')
    for name, data, iters in CASES:
        print(f'  {name:10s} {len(data):6d} -> {len((HERE / (name + ".z")).read_bytes()):6d}'
              f'  (-m{RING_SMALL}: {len((HERE / (name + ".r")).read_bytes()):6d},'
              f' -m{RING_FAIR}: {len((HERE / (name + ".r1024")).read_bytes()):6d})'
              f'  x{iters}')


if __name__ == '__main__':
    main()
