#!/usr/bin/env python3
"""Builds the tune and the expected result the Hatari harness is assembled with.

Packs a synthetic YM6 tune with the real Java packer and writes yx6data.inc:
the frame count, the ring size, and the checksum of everything the sound chip
should hold after every frame - computed here, from the YM data, with no
knowledge of how the player works.

    python3 yx6/test/gendata.py
"""
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
CLASSES = REPO / 'target' / 'classes'

sys.path.insert(0, str(HERE))
import gen_ym                                                       # noqa: E402

FRAMES = 1500
RING = 1024
CHUNK = 16


def chip_checksum(frames: int, source) -> int:
    """Fold what a YM2149 would read back after each frame into one long.

    Registers keep their value until written again, which is what makes R13
    interesting: on a frame that says "leave the envelope alone" the chip still
    reads back the shape from an earlier frame.
    """
    state = [0] * gen_ym.PLAY_REGISTERS
    checksum = 0
    for writes in gen_ym.expected_writes(frames, source):
        for register, value in writes:
            state[register] = value
        for value in state:
            checksum = ((checksum << 1) & 0xFFFFFFFF) | (checksum >> 31)
            checksum ^= value
    return checksum


def main() -> int:
    if not CLASSES.exists():
        raise SystemExit('target/classes is missing; run `mvn compile` first')

    source = gen_ym.registers(FRAMES)
    tune = HERE / 'tune.ym'
    tune.write_bytes(gen_ym.ym6_file(FRAMES, source))
    packed = HERE / 'tune.yx6'
    subprocess.run(['java', '-ea', '-cp', str(CLASSES), 'org.yx6.Yx6', '-f',
                    f'-n{RING}', f'-c{CHUNK}', str(tune), str(packed)],
                   check=True, capture_output=True)

    checksum = chip_checksum(FRAMES, source)
    (HERE / 'yx6data.inc').write_text(f"""; Generated by yx6/test/gendata.py - do not edit.
; A synthetic {FRAMES}-frame tune, packed by the Java yx6 tool, and the
; checksum of the sound chip's contents after every frame.
YX6_FRAMES  equ     {FRAMES}
RING_SIZE   equ     {RING}
YX6_CHUNK   equ     {CHUNK}
YX6_SUM     equ     ${checksum:08X}

        .data
        even
song:
        incbin  "tune.yx6"
        even
""")
    print(f'tune.yx6: {packed.stat().st_size} bytes, {FRAMES} frames, '
          f'{RING}-byte rings, checksum ${checksum:08X}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
