#!/bin/sh
# mkprg.sh - build a runnable Atari ST program from a packed .yx6 tune.
#
#   yx6/mkprg.sh song.yx6 [SONG.PRG]
#
# Writes a two-line wrapper around YX6_player.S (a VBL front end), YX6.S (the
# player library) and ST1_wrap.S (the decoder), and assembles the lot into a
# TOS program with rmac. The ring size comes out of the file's own header, so
# the workspace the program reserves always matches the tune it carries.
#
# Needs rmac on PATH. Pack the tune first, for example:
#   mvn -q compile exec:exec@yx6 -Dargs="-f song.ym song.yx6"
set -e

YX6_DIR=$(cd "$(dirname "$0")" && pwd)
REPO=$(cd "$YX6_DIR/.." && pwd)

song=$1
if [ -z "$song" ]; then
    echo "usage: mkprg.sh song.yx6 [SONG.PRG]" >&2
    exit 1
fi
if [ ! -f "$song" ]; then
    echo "mkprg.sh: no such file: $song" >&2
    exit 1
fi
song_path=$(cd "$(dirname "$song")" && pwd)/$(basename "$song")

# Default output name: the song's, upper-cased and cut to the 8.3 a TOS
# filesystem shows, so the .PRG is usable straight off a floppy image.
if [ -n "$2" ]; then
    output=$2
else
    stem=$(basename "$song" .yx6 | tr 'a-z-' 'A-Z_' | cut -c1-8)
    output=$(dirname "$song")/$stem.PRG
fi

byte() {                                    # one unsigned byte at offset $1
    od -An -tu1 -j "$1" -N1 "$song_path" | tr -d ' \n'
}

magic=$(od -An -c -j0 -N4 "$song_path" | tr -d ' \n')
if [ "$magic" != "YX6!" ]; then
    echo "mkprg.sh: $song is not a yx6 file (it starts with \"$magic\")" >&2
    exit 1
fi
ring=$(( $(byte 16) * 256 + $(byte 17) ))   # header: N at 16, C at 18
chunk=$(( $(byte 18) * 256 + $(byte 19) ))
# Big-endian by hand: od -tu4 would read it in the host's byte order.
frames=$(( ($(byte 8) * 16777216) + ($(byte 9) * 65536) \
         + ($(byte 10) * 256) + $(byte 11) ))
echo "$song: $frames frames, ${ring}-byte rings, $chunk values per call"

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

# The wrapper binds the only two things that depend on this song: how much
# workspace to reserve, and which file to embed.
cat > "$work/wrapper.S" <<EOF
; Generated by yx6/mkprg.sh from $(basename "$song") - do not edit.
RING_SIZE   equ     $ring
        include "YX6_player.S"

        .data
        even
song:
        incbin  "$song_path"
        even
EOF

rmac -m68000 -p +o3 -i"$YX6_DIR" -i"$REPO/68k" -o "$output" "$work/wrapper.S"
echo "$output: $(wc -c < "$output" | tr -d ' ') bytes"
