<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>djx1</AssemblyName>
    <PackageId>Jx1.Decompressor.Tool</PackageId>
    <RootNamespace>Jx1.CommandLine</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Jx1/Jx1.csproj" />
  </ItemGroup>
</Project>
